cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

jwt:
  secret-key: "4c092f4c787e11b95b1b6fd9cb0759257e9ae840febfd21622d475a509c7ba77"
  expire-after: "86400000"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "IssueCrush"

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/issuecrush
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect